@url=http://localhost:3000


### promedios de Alumno
GET {{url}}/promedios

### Post de promedios
POST {{url}}/promedios
Content-Type: application/json

{
    "nombre": "Martina",
    "notas": [5, 9, 9]
}

